import = [
	"~/.config/alacritty/themes/flexoki-light.toml"
]

[font]
size = 10

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[window]
# opacity = 0.9
padding = { x = 8, y = 8 }
