# Default colors
[colors.primary]
background = '#0A0A0A'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#0A0A0A'
red     = '#d71a1a'
green   = '#028157'
yellow  = '#a36118'
blue    = '#2f2fdf'
magenta = '#b77ee0'
cyan    = '#b7cbf4'
white   = '#dedede'

# Bright colors
[colors.bright]
black   = '#2A2A2A'
red     = '#d78787'
green   = '#5fd7af'
yellow  = '#d7d787'
blue    = '#567cce'
magenta = '#a3a3eb'
cyan    = '#a9c1de'
white   = '#eeeeee'

[font]
size = 12 

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[colors.cursor]
text = '#1E1E1E'
cursor = '#CF73E6'

#[window]
#blur = true
#opacity = 0.9
