general.import = [
	"~/.config/alacritty/themes/nvim-dark.toml"
]

[font]
size = 10

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

#[window]
#padding = { x = 8, y = 8 }
