[colors.primary]
background = '#14161B'
foreground = '#E0E2EA'

[colors.cursor]
text = "#121212"
cursor = "#D81860"

[colors.normal]
black = "#121212"
red = "#F44747"
green = "#B3F6C0"
yellow = "#FCE094"
blue = "#59B3FB"
magenta = "#D81860"
cyan = "#A6DBFF"
white = "#D4D4D4"

[colors.bright]
black = "#2C2E33" 
red = "#F44747"
green = "#B3F6C0"
yellow = "#FCE094"
blue = "#59B3FB"
magenta = "#D81860"
cyan = "#A6DBFF"
white = "#E0E2EA"

[font]
size = 10 

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[window]
padding = { x = 2, y = 2 }
