# Colors (Belafonte Day)
import = [
	"~/.config/alacritty/themes/acme.toml"
]

[font]
size = 11 #85660B

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[window]
padding = { x = 3, y = 3 }
