[colors.bright]
black = '#464646'
blue = '#0a84ff'
cyan = '#76d6ff'
green = '#32d74b'
magenta = '#bf5af2'
red = '#ff453a'
white = '#ffffff'
yellow = '#ffd60a'

[colors.normal]
black = '#1a1a1a'
blue = '#0869cb'
cyan = '#479ec2'
green = '#26a439'
magenta = '#9647bf'
red = '#cc372e'
white = '#98989d'
yellow = '#cdac08'

[colors.primary]
background = '#1e1e1e'
foreground = '#ffffff'

[colors.selection]
background = '#3f638b'
text = '#ffffff'

[font]
size = 12 

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[colors.cursor]
text = '#1E1E1E'
cursor = '#CF73E6'

#[window]
#blur = true
#opacity = 0.9
