# Spacecamp

# Default colors
[colors.primary]
background = '#121212'
foreground = '#d0d0d0'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#d71a1a'
green   = '#57ba37'
yellow  = '#f0d50c'
blue    = '#91aadf'
magenta = '#cf73e6'
cyan    = '#b7cbf4'
white   = '#dedede'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#ff0000'
green   = '#d8fa3b'
yellow  = '#e7c547'
blue    = '#b7cbf4'
magenta = '#b77ee0'
cyan    = '#a9c1de'
white   = '#eeeeee'

[font]
size = 15 

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[window]
opacity = 0.8
