# Default colors
[colors.primary]
background = '#1E1E1E'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#C01C28'
green   = '#2EC27E'
yellow  = '#F5C211'
blue    = '#1E78E4'
magenta = '#9841BB'
cyan    = '#0AB9DC'
white   = '#C0BFBC'

# Bright colors
[colors.bright]
black   = '#5E5C64'
red     = '#ED333B'
green   = '#57E389'
yellow  = '#F8E45C'
blue    = '#51A1FF'
magenta = '#C061CB'
cyan    = '#4FD2FD'
white   = '#ffffff'

[font]
size = 10 

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[window]
#padding = { x = 2, y = 2 }
