# XTerm's default colors

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

# Bright colors
[colors.bright]
black   = '#7f7f7f'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#5c5cff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'

[font]
size = 16 

[font.bold]
family = "hasklig"
style = "Bold"

[font.bold_italic]
family = "hasklig"
style = "Bold Italic"

[font.italic]
family = "hasklig"
style = "Italic"

[font.normal]
family = "hasklig"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 3, y = 3 }
