# Default colors
[colors.primary]
background = '#323131'
foreground = '#e6e6fa'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#C01C28'
green   = '#6daf22'
yellow  = '#F8E45C'
blue    = '#1E78E4'
magenta = '#C061CB'
cyan    = '#4FD2FD'
white   = '#e6e6fa'

# Bright colors
[colors.bright]
black   = '#5E5C64'
red     = '#ED333B'
green   = '#6daf22'
yellow  = '#F8E45C'
blue    = '#51A1FF'
magenta = '#C061CB'
cyan    = '#4FD2FD'
white   = '#ffffff'

[font]
size = 12 

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[colors.cursor]
text = '#1E1E1E'
cursor = '#CF73E6'

#[window]
#blur = true
#opacity = 0.9
