# ~/.config/starship.toml

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[%](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[*](bold blue)"

[cmd_duration]
disabled = true

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold yellow) '
trim_at = '.companyname.com'
disabled = false
