# ~/.config/starship.toml

add_newline = false

[cmd_duration]
disabled = true

[username]
style_user = 'bold bright-purple'
style_root = 'bold red'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold bright-blue)@[$hostname](bold yellow underline) '
trim_at = '.companyname.com'
disabled = false

[line_break]
disabled = true

[character]
success_symbol = "[%](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[*](bold blue)"

[cmd_duration]
disabled = true

