add_newline = false

# Use custom format
format = """
$status$username$hostname$directory$git_branch$git_commit$git_commit$git_state$git_status
$character
"""

[status]
style = 'fg:bright-red'
format = '[$common_meaning:$int ]($style)'
disabled = false

[username]
style_user = 'underline bold fg:bright-white'
style_root = 'underline bold fg:red'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
style = 'bold fg:bright-blue'
ssh_only = false
ssh_symbol = ' via ssh'
format = '[@$hostname]($style)[$ssh_symbol]($style)'
trim_at = '.companyname.com'
disabled = false

[directory]
style = ' fg:bright-cyan'
format = ' in[ $path ]($style)'
truncation_length = 3
read_only = "ro"

[git_branch]
style = 'bold fg:bright-purple'
format = 'on [\(($branch(:$remote_branch))\)]($style)'

[cmd_duration]
disabled = false

[line_break]
disabled = false

[character]
success_symbol = "[>](bold fg:bright-purple)"
error_symbol = "[x](bold fg:red)"
vimcmd_symbol = "[*](bold fg:bright-blue)"

[git_commit]
style = 'bg:green bold fg:bright-white'
tag_symbol = "[ tag ]($style)"

[git_state]
style = 'bold fg:bright-white'
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = ' fg:yellow'
format = ' ([\[$all_status$ahead_behind\]]($style))'
staged = '[+$count](bold bright-green)'
stashed = 's'
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = '[ x ](strikethrough bright-red)'
