add_newline = false

# Use custom format
format = """
$status$username$hostname$directory$git_branch$git_commit$git_commit$git_state$git_status
$character
"""

[status]
style = 'bg:#504945 fg:#FB4934'
format = '[ $common_meaning:$int]($style)'
disabled = false

[username]
style_user = 'bg:#504945 fg:#EBDBB2'
style_root = 'bg:#504945 bold fg:#FB4934'
format = '[ $user]($style)'
disabled = false
show_always = true

[hostname]
style = 'bg:#504945 bold fg:#FABD2F'
ssh_only = false
format = '[$ssh_symbol]($style)[@$hostname]($style)'
trim_at = '.companyname.com'
disabled = false

[directory]
style = 'bg:#504945 fg:#EBDBB2'
format = '[ in $path ]($style)'
truncation_length = 3
read_only = "ro"

[git_branch]
style = 'bg:#A89984 bold fg:#282828'
format = '[ ($branch(:$remote_branch)) ]($style)'

[cmd_duration]
disabled = false

[line_break]
disabled = false

[character]
success_symbol = "[>](bold fg:#B16286)"
error_symbol = "[x](bold fg:#CC241D)"
vimcmd_symbol = "[*](bold fg:#83A598)"

[git_commit]
style = 'bg:#8EC07C bold fg:#EBDBB2'
tag_symbol = "[ tag ]($style)"

[git_state]
style = 'bg:#D3869B bold fg:#EBDBB2'
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = 'bg:#FE8019 fg:#282828'
format = '([ $all_status$ahead_behind ]($style))'
staged = '+$count'
stashed = 's'
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
