add_newline = false

# Use custom format
format = '''
[╭─](fg:#44475A)$directory$git_branch$git_status$fill$status[|](bg:#44475A)$time[](fg:#44475A)
[╰─](fg:#44475A) '''

[time]
disabled = false
style = 'bg:#44475A'
format = '[ $time]($style)'
time_format = '%H:%M:%S'

[fill]
symbol = ' '
#style = 'bg:#44475A'

[status]
style = 'bg:#44475A'
not_found_symbol = "[ ✗ ](bold fg:bright-red bg:#44475A)"
symbol = "[ ✗ ](bold fg:bright-red bg:#44475A)"
not_executable_symbol = "[ ✗ ](bold fg:bright-red bg:#44475A)"
sigint_symbol = "[ ✗ ](bold fg:bright-red bg:#44475A)"
signal_symbol = "[ ! ](bold fg:yellow bg:#44475A)"
success_symbol = "[ ✓ ](bold fg:bright-green bg:#44475A)"
format = '[$symbol]($style)'
map_symbol = true
disabled = false

[directory]
style = 'bg:#44475A'
format = '[$path ]($style)'
truncation_length = 3
read_only = 'ro '

[git_branch]
style = 'bold fg:black bg:bright-blue'
format = '[ ($branch(:$remote_branch)) ]($style)'

[cmd_duration]
disabled = false

[line_break]
disabled = false

[git_commit]
style = 'bg:#6272A4 bold fg:green'
tag_symbol = "[ tag ]($style)"

[git_state]
style = 'bold fg:bright-white'
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = 'bold fg:yellow bg:#6272A4'
format = '([ $stashed$staged$modified$deleted ]($style))'
staged = '[+$count](bold bright-green bg:#6272A4)'
stashed = 'S'
modified = '[~$count](bold fg:#FFB86C bg:#6272A4)'
deleted = '[-$count](bold fg:bright-red bg:#6272A4)'
