[colors.primary]
background = "#F6F5F4"
foreground = "#100F0F"

# Cursor colors
[colors.cursor]
text = "#F6F5F4"
cursor = "#8759B5"

# Normal colors
[colors.normal]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#F6F5F4"

# Bright colors
[colors.bright]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#F6F5F4"

# Dim colors
[colors.dim]
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#F6F5F4"

