# Colors (Seoul256)
[colors.primary]
background= '#171717'
foreground= '#d0d0d0'

[colors.normal]
black=   '#060606'
red=     '#d68787'
green=   '#5f865f'
yellow=  '#d8af5f'
blue=    '#85add4'
magenta= '#d7afaf'
cyan=    '#87afaf'
white=   '#d0d0d0'

[colors.bright]
black=   '#626262'
red=     '#d75f87'
green=   '#87af87'
yellow=  '#ffd787'
blue=    '#add4fb'
magenta= '#ffafaf'
cyan=    '#87d7d7'
white=   '#e4e4e4'

